name: Docker

on:
  workflow_call:

jobs:
  build:
    strategy:
      matrix:
        include:
          - version: stable
            latest: false
          - version: beta
            latest: false
          - version: nightly
            latest: false
          - version: 1.77
            latest: true
          - version: 1.76
            latest: false
    uses: "./.github/workflows/docker-images.yml"
    with:
        version: ${{ matrix.version }}
        latest: ${{ matrix.latest }}
        node_version: "20"
