name: Docker

on:
  workflow_call:

jobs:
  build:
    strategy:
      matrix:
        include:
          - version: stable
            latest: false
          - version: beta
            latest: false
          - version: nightly
            latest: false
          - version: 1.77
            latest: true
          - version: 1.76
            latest: false
    uses: "tweedegolf/actions-container-helpers/.github/workflows/container-image.yml@main"
    with:
        push: ${{ github.ref == 'refs/heads/main' }}
        platforms: "linux/amd64,linux/arm64"
        build-args: |
          RUSTUP_VERSION=1.27.0
          RUSTUP_SHA256_AMD64=a3d541a5484c8fa2f1c21478a6f6c505a778d473c21d60a18a4df5185d320ef8
          RUSTUP_SHA256_ARM64=76cd420cb8a82e540025c5f97bda3c65ceb0b0661d5843e6ef177479813b0367
          CARGO_BINSTALL_VERSION=1.6.4
          CARGO_BINSTALL_SHA256_AMD64=b07160c21cdfcc24c3afe94b3cb12bf6d111cef7b218cce85a0c1dfae7e106dd
          CARGO_BINSTALL_SHA256_ARM64=70c17459e4bc0b417679e66af55199603d80fa751d819b86713f700e3e9a6602
          SCCACHE_VERSION=0.7.7
          SCCACHE_SHA256_AMD64=ed0010b4dcaccce42b9dc8699257134a113d0ca16dfb7db890356135218322c9
          SCCACHE_SHA256_ARM64=e7ecabac9a703e53a8b06e84b0058fcf242239d164050537bc399387160320fb
          CARGO_UDEPS_VERSION=0.1.47
          CARGO_UDEPS_SHA256_AMD64=d98267271652f87c3516bf8623ebd86a3afcada304714e47cacdb0a96bb6df0c
          CARGO_UDEPS_SHA256_ARM64=445c6ef1325d247a1e31481d34ecdd5a7ae87f702aff40cfa9dd8ce2ea8f2783
          RUST_VERSION=${{matrix.version}}
        tags: |
            ghcr.io/tweedegolf/rust-dev:${{matrix.version}}
            ${{ matrix.latest && 'ghcr.io/tweedegolf/rust-dev:latest' || '' }}
